export const lightTokens = {
  bgBase: "#FAFAF9",
  bgSurface: "#FFFFFF",
  bgSurfaceAlt: "#F5F4F2",
  bgSunken: "#EFEDE9",
  borderSubtle: "#E8E5E0",
  borderDefault: "#D4CFC8",
  borderStrong: "#B5AFA6",
  textPrimary: "#1A1714",
  textSecondary: "#6B6560",
  textMuted: "#9E9892",
  textInverse: "#FFFFFF",
  brandBase: "#3B5BDB",
  brandHover: "#3451C7",
  brandSubtle: "#EEF2FF",
  brandMuted: "#C5D0FA",
  successBase: "#2F9E44",
  successSubtle: "#EBFBEE",
  successMuted: "#B2F2BB",
  successText: "#1E6B2E",
  warningBase: "#E67700",
  warningSubtle: "#FFF9DB",
  warningMuted: "#FFE066",
  warningText: "#7D4A00",
  dangerBase: "#E03131",
  dangerSubtle: "#FFF5F5",
  dangerMuted: "#FFC9C9",
  dangerText: "#B02020",
} as const;

export type ThemeTokens = typeof lightTokens;
